### ISSUE TITLE
Error turning on Gpio on Orangepi Lite 

### ISSUE THREAD

**Issue by ajaybnl** [Blue-Beaker/OctoPrint-PSUControl-OPi.GPIO#1]
Error while turning on gpio: 
i have already 

2023-02-24 12:05:33,893 - octoprint.plugins.psucontrol - INFO - Switching PSU Off
2023-02-24 12:05:33,894 - octoprint.plugins.psucontrol_opigpio - ERROR - Exception while writing GPIO line
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_opigpio/__init__.py", line 207, in turn_psu_off
    GPIO.output(self._gpio_get_pin(self.config['onoffGPIOPin']), o)
  File "/home/pi/oprint/lib/python3.9/site-packages/OPi/GPIO.py", line 524, in output
    _check_configured(channel, direction=OUT)
  File "/home/pi/oprint/lib/python3.9/site-packages/OPi/GPIO.py", line 374, in _check_configured
    raise RuntimeError("Channel {0} is not configured".format(channel))
RuntimeError: Channel 4 is not configured

**Comment by robinson01** [comment]
if anyone else wanders here, this solved the problem for me: 
https://community.octoprint.org/t/psu-control-rpi-gpio-for-orangepi/35166
